address = "xxx.com"
port = "8080"

mysql.dsn = "%s:%s@tcp(127.0.0.1:3306)/%s?charset=utf8mb4&parseTime=True&loc=Local"
mysql.user = "root"
mysql.pass = "haoran232"
mysql.dbname = "wx_login"

logger.level = "info"     # debug info warn error dpanic panic fatal

session.name = "wx-login"
session.path = "" # os.TempDir() if ""
session.secret = "123456"

applet.url = "xxx.com/xxx"
applet.code2sessionKeyUrl = "https://api.weixin.qq.com/sns/jscode2session?appid=%s&secret=%s&js_code=%s&grant_type=authorization_code"
applet.id = ""
applet.secret = ""
